FEAT: #33 load product detail and make random and dislike button
six-sense/1_mrCamel_team1 pull request #39
Opened 2021-07-30 08:52 UTC by yh1120

상세페이지 기능들을 만들었습니다.
기본적으로 /product/:productId 에 해당하는 productId의 내용을 불러와 화면에 띄웁니다.
dislike 버튼을 누르면 localStorage에 interestList가 있는지 확인하고, 없으면 새로 만들면서 현재 productId를 제외한 나머지를 localStorage에 갱신합니다.
랜덤버튼을 누르면 interestList에 있는 productId 중 1개를 골라 새로운 페이지로 로드합니다.
여기서도 마찬가지로 localStorage가 없으면 새로 만들어주고, 만약 interestList의 value가 비어있다면 작동하지 않습니다.

2021-07-30 11:35 UTC, tTab1204 commented on src/pages/ProductDetailPage.js
> +      return { productId: parseInt(nextProps.match.params.productId) };
고생 많으셨어요! `nextProps.match.params.productId`가 중복되는데 따로 변수로 선언해서 사용하는건 어떠실까요? 
리뷰가 올라간 줄 알았는데 안 올라갔었네요 ㅠㅠ 늦어서 죄송합니다..!

2021-07-30 13:12 UTC, yh1120 commented
말씀하신 것 반영하겠습니다!

2021-07-30 15:11 UTC, tTab1204 requested changes

2021-07-30 15:11 UTC, tTab1204 commented on src/pages/ProductDetailPage.js
> +      return `/product/${interestList[randomProduct]}`;
`Link to={경로}` 에는 보통 함수가 아닌 path가 들어가는 걸로 알고 있습니다. 함수에서 경로를 이동하는 것을 지정해야 할 때는 `history`를 사용하면 될 것 같습니다.

제 PC에서 테스트했을 때는 문제 없이 동작하는 코드입니다.
따로 return 해줄 필요 없이 이렇게 바꾸면 더 좋을 것 같습니다! >> `this.props.history.push(`/product/${randomProduct}`);`

2021-07-30 15:11 UTC, tTab1204 commented on src/pages/ProductDetailPage.js
> +            <Link to={handleRandom}>Random</Link>
위와 연결되는 부분입니다! `history`를 통해 이동하기 때문에
`<Button onClick={handleRandom}>Random</Button>`
이런 식으로 버튼으로 바꾸면 좋을 것 같습니다.

- Button은 ant-design에서 import 해왔습니다.

2021-07-30 15:19 UTC, tTab1204 requested changes

2021-07-30 15:19 UTC, tTab1204 commented on src/pages/ProductDetailPage.js
> +      LOCAL_STORAGE.set("interestList", tempArray);
54번 라인부터 
```js
if (interestList.length <= 0) {
        return;
      }
      const randomProduct = Math.floor(Math.random() * interestList.length);
      console.log("randomProduct: ", randomProduct);

      this.props.history.push(`/product/${randomProduct}`);
```
이 로직을 추가해서 싫어요 눌렀을 시 상품이 랜덤으로 바뀌어야 할 것 같습니다!

2021-07-30 17:10 UTC, yh1120 commented on src/pages/ProductDetailPage.js
> +      LOCAL_STORAGE.set("interestList", tempArray);
하다가 계속 안 돼서 내일 다시 해보도록 하겠습니다 ㅠㅠ 이 글을 미리 봤으면 좋았을 것 같아요 ㅠㅠ

2021-07-30 23:04 UTC, yisu-kim commented on src/pages/ProductDetailPage.js
> +      return `/product/${interestList[randomProduct]}`;
react-router-dom 문서 보시면 to에 함수 사용하는 법 나와 있습니다.
이 방법도 참고해보시면 좋을 것 같아요.
https://reactrouter.com/web/api/Link/to-function

2021-07-31 00:33 UTC, tTab1204 commented on src/pages/ProductDetailPage.js
> +      LOCAL_STORAGE.set("interestList", tempArray);
이전에도 기능상 문제는 없어서(랜덤기능) 괜찮을 것 같아서 따로 리뷰를 안했었는데 미리 말씀을 드릴 걸 그랬네요 ㅠㅠ

2021-07-31 02:42 UTC, merged

2021-07-31 02:44 UTC, yh1120 commented
history.push를 통해 페이지가 전환되고, nextProps에서 해당하는 productId를 가져오도록 했습니다.
불필요한 기능은 제거되었고, 오작동되던 randomProduct 함수를 수정했습니다.